#ifndef __SimpleWork_Module_h__
#define __SimpleWork_Module_h__

__SimpleWork_Core_Namespace_Enter__

SIMPLEWORK_CLASS_ENTER(Module)

SIMPLEWORK_CLASS_LEAVE

__SimpleWork_Core_Namespace_Leave__

#endif//__SimpleWork_Module_h__