#ifndef __SimpleWork_Object_h__
#define __SimpleWork_Object_h__

__SimpleWork_Core_Namespace_Enter__

SIMPLEWORK_CLASS_ENTER(Object)
SIMPLEWORK_CLASS_LEAVE

__SimpleWork_Core_Namespace_Leave__

#endif//__SimpleWork_Object_h__